// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezjkxcinrmothhjculyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6amt4Y2lucm1vdGhoamN1bHlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODkxNjksImV4cCI6MjA3MDE2NTE2OX0._x5Uqg30aQpU9clVIRHRmwdunHhdU6aWzkcI-LCtYV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});